services:
  - type: web
    name: finan-wallet-admin
    env: node
    plan: starter
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: NEXT_PUBLIC_API_URL
        value: "https://finan-wallet-backend.onrender.com/api"
